// Code generated by MockGen. DO NOT EDIT.
// Source: attachment_service.go
//
// Generated by this command:
//
//	mockgen -source=attachment_service.go -destination=../../test/svcmocks/attachment_service_mock.go -package=svcmocks
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	io "io"
	reflect "reflect"

	model "github.com/dexiask/dexiask/internal/model"
	service "github.com/dexiask/dexiask/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockAttachmentService is a mock of AttachmentService interface.
type MockAttachmentService struct {
	ctrl     *gomock.Controller
	recorder *MockAttachmentServiceMockRecorder
	isgomock struct{}
}

// MockAttachmentServiceMockRecorder is the mock recorder for MockAttachmentService.
type MockAttachmentServiceMockRecorder struct {
	mock *MockAttachmentService
}

// NewMockAttachmentService creates a new mock instance.
func NewMockAttachmentService(ctrl *gomock.Controller) *MockAttachmentService {
	mock := &MockAttachmentService{ctrl: ctrl}
	mock.recorder = &MockAttachmentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttachmentService) EXPECT() *MockAttachmentServiceMockRecorder {
	return m.recorder
}

// ListByConversation mocks base method.
func (m *MockAttachmentService) ListByConversation(ctx context.Context, conversationID string) ([]*model.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByConversation", ctx, conversationID)
	ret0, _ := ret[0].([]*model.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByConversation indicates an expected call of ListByConversation.
func (mr *MockAttachmentServiceMockRecorder) ListByConversation(ctx, conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByConversation", reflect.TypeOf((*MockAttachmentService)(nil).ListByConversation), ctx, conversationID)
}

// Open mocks base method.
func (m *MockAttachmentService) Open(ctx context.Context, id string) (io.ReadCloser, *model.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, id)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(*model.Attachment)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Open indicates an expected call of Open.
func (mr *MockAttachmentServiceMockRecorder) Open(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockAttachmentService)(nil).Open), ctx, id)
}

// Reconcile mocks base method.
func (m *MockAttachmentService) Reconcile(ctx context.Context, uploadBucket, conversationID, messageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconcile", ctx, uploadBucket, conversationID, messageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockAttachmentServiceMockRecorder) Reconcile(ctx, uploadBucket, conversationID, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MockAttachmentService)(nil).Reconcile), ctx, uploadBucket, conversationID, messageID)
}

// Store mocks base method.
func (m *MockAttachmentService) Store(ctx context.Context, in service.StoreInput) (*model.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, in)
	ret0, _ := ret[0].(*model.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Store indicates an expected call of Store.
func (mr *MockAttachmentServiceMockRecorder) Store(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockAttachmentService)(nil).Store), ctx, in)
}
