// Code generated by MockGen. DO NOT EDIT.
// Source: auth_service.go
//
// Generated by this command:
//
//	mockgen -source=auth_service.go -destination=../../test/svcmocks/auth_service_mock.go -package=svcmocks
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"

	model "github.com/dexiask/dexiask/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// Complete mocks base method.
func (m *MockAuthService) Complete(ctx context.Context, code string) (string, *model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, code)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*model.User)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Complete indicates an expected call of Complete.
func (mr *MockAuthServiceMockRecorder) Complete(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockAuthService)(nil).Complete), ctx, code)
}

// CreateInvite mocks base method.
func (m *MockAuthService) CreateInvite(ctx context.Context, login, createdBy string) (*model.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvite", ctx, login, createdBy)
	ret0, _ := ret[0].(*model.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvite indicates an expected call of CreateInvite.
func (mr *MockAuthServiceMockRecorder) CreateInvite(ctx, login, createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvite", reflect.TypeOf((*MockAuthService)(nil).CreateInvite), ctx, login, createdBy)
}

// DeleteInvite mocks base method.
func (m *MockAuthService) DeleteInvite(ctx context.Context, login string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInvite", ctx, login)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInvite indicates an expected call of DeleteInvite.
func (mr *MockAuthServiceMockRecorder) DeleteInvite(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInvite", reflect.TypeOf((*MockAuthService)(nil).DeleteInvite), ctx, login)
}

// ListInvites mocks base method.
func (m *MockAuthService) ListInvites(ctx context.Context) ([]*model.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvites", ctx)
	ret0, _ := ret[0].([]*model.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvites indicates an expected call of ListInvites.
func (mr *MockAuthServiceMockRecorder) ListInvites(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvites", reflect.TypeOf((*MockAuthService)(nil).ListInvites), ctx)
}

// ListUsers mocks base method.
func (m *MockAuthService) ListUsers(ctx context.Context) ([]*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx)
	ret0, _ := ret[0].([]*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockAuthServiceMockRecorder) ListUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockAuthService)(nil).ListUsers), ctx)
}

// LoginURL mocks base method.
func (m *MockAuthService) LoginURL(state string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginURL", state)
	ret0, _ := ret[0].(string)
	return ret0
}

// LoginURL indicates an expected call of LoginURL.
func (mr *MockAuthServiceMockRecorder) LoginURL(state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginURL", reflect.TypeOf((*MockAuthService)(nil).LoginURL), state)
}

// Logout mocks base method.
func (m *MockAuthService) Logout(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthServiceMockRecorder) Logout(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthService)(nil).Logout), ctx, sessionID)
}

// Me mocks base method.
func (m *MockAuthService) Me(ctx context.Context, userID string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Me", ctx, userID)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Me indicates an expected call of Me.
func (mr *MockAuthServiceMockRecorder) Me(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Me", reflect.TypeOf((*MockAuthService)(nil).Me), ctx, userID)
}

// TokenLogin mocks base method.
func (m *MockAuthService) TokenLogin(ctx context.Context, token string) (string, *model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenLogin", ctx, token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*model.User)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// TokenLogin indicates an expected call of TokenLogin.
func (mr *MockAuthServiceMockRecorder) TokenLogin(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenLogin", reflect.TypeOf((*MockAuthService)(nil).TokenLogin), ctx, token)
}
