// Code generated by MockGen. DO NOT EDIT.
// Source: chat_service.go
//
// Generated by this command:
//
//	mockgen -source=chat_service.go -destination=../../test/svcmocks/chat_service_mock.go -package=svcmocks
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"

	agent "github.com/dexiask/dexiask/internal/agent"
	service "github.com/dexiask/dexiask/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockTxRunner is a mock of TxRunner interface.
type MockTxRunner struct {
	ctrl     *gomock.Controller
	recorder *MockTxRunnerMockRecorder
	isgomock struct{}
}

// MockTxRunnerMockRecorder is the mock recorder for MockTxRunner.
type MockTxRunnerMockRecorder struct {
	mock *MockTxRunner
}

// NewMockTxRunner creates a new mock instance.
func NewMockTxRunner(ctrl *gomock.Controller) *MockTxRunner {
	mock := &MockTxRunner{ctrl: ctrl}
	mock.recorder = &MockTxRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxRunner) EXPECT() *MockTxRunnerMockRecorder {
	return m.recorder
}

// InTransaction mocks base method.
func (m *MockTxRunner) InTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// InTransaction indicates an expected call of InTransaction.
func (mr *MockTxRunnerMockRecorder) InTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InTransaction", reflect.TypeOf((*MockTxRunner)(nil).InTransaction), ctx, fn)
}

// MockChatService is a mock of ChatService interface.
type MockChatService struct {
	ctrl     *gomock.Controller
	recorder *MockChatServiceMockRecorder
	isgomock struct{}
}

// MockChatServiceMockRecorder is the mock recorder for MockChatService.
type MockChatServiceMockRecorder struct {
	mock *MockChatService
}

// NewMockChatService creates a new mock instance.
func NewMockChatService(ctrl *gomock.Controller) *MockChatService {
	mock := &MockChatService{ctrl: ctrl}
	mock.recorder = &MockChatServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatService) EXPECT() *MockChatServiceMockRecorder {
	return m.recorder
}

// Resume mocks base method.
func (m *MockChatService) Resume(ctx context.Context, conversationID string) (*agent.Run, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resume", ctx, conversationID)
	ret0, _ := ret[0].(*agent.Run)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Resume indicates an expected call of Resume.
func (mr *MockChatServiceMockRecorder) Resume(ctx, conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resume", reflect.TypeOf((*MockChatService)(nil).Resume), ctx, conversationID)
}

// Start mocks base method.
func (m *MockChatService) Start(ctx context.Context, req service.ChatRequest) (*service.ChatStartResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, req)
	ret0, _ := ret[0].(*service.ChatStartResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockChatServiceMockRecorder) Start(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockChatService)(nil).Start), ctx, req)
}

// Stop mocks base method.
func (m *MockChatService) Stop(conversationID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", conversationID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockChatServiceMockRecorder) Stop(conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockChatService)(nil).Stop), conversationID)
}

// MockMemoryDigester is a mock of MemoryDigester interface.
type MockMemoryDigester struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryDigesterMockRecorder
	isgomock struct{}
}

// MockMemoryDigesterMockRecorder is the mock recorder for MockMemoryDigester.
type MockMemoryDigesterMockRecorder struct {
	mock *MockMemoryDigester
}

// NewMockMemoryDigester creates a new mock instance.
func NewMockMemoryDigester(ctrl *gomock.Controller) *MockMemoryDigester {
	mock := &MockMemoryDigester{ctrl: ctrl}
	mock.recorder = &MockMemoryDigesterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemoryDigester) EXPECT() *MockMemoryDigesterMockRecorder {
	return m.recorder
}

// Digest mocks base method.
func (m *MockMemoryDigester) Digest(ctx context.Context, userID string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Digest", ctx, userID)
	ret0, _ := ret[0].(string)
	return ret0
}

// Digest indicates an expected call of Digest.
func (mr *MockMemoryDigesterMockRecorder) Digest(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Digest", reflect.TypeOf((*MockMemoryDigester)(nil).Digest), ctx, userID)
}
