// Code generated by MockGen. DO NOT EDIT.
// Source: conversation_service.go
//
// Generated by this command:
//
//	mockgen -source=conversation_service.go -destination=../../test/svcmocks/conversation_service_mock.go -package=svcmocks
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"

	model "github.com/dexiask/dexiask/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockConversationService is a mock of ConversationService interface.
type MockConversationService struct {
	ctrl     *gomock.Controller
	recorder *MockConversationServiceMockRecorder
	isgomock struct{}
}

// MockConversationServiceMockRecorder is the mock recorder for MockConversationService.
type MockConversationServiceMockRecorder struct {
	mock *MockConversationService
}

// NewMockConversationService creates a new mock instance.
func NewMockConversationService(ctrl *gomock.Controller) *MockConversationService {
	mock := &MockConversationService{ctrl: ctrl}
	mock.recorder = &MockConversationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConversationService) EXPECT() *MockConversationServiceMockRecorder {
	return m.recorder
}

// GetMessages mocks base method.
func (m *MockConversationService) GetMessages(ctx context.Context, workspaceID, userID, conversationID string) ([]*model.MessageWithAttachments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", ctx, workspaceID, userID, conversationID)
	ret0, _ := ret[0].([]*model.MessageWithAttachments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockConversationServiceMockRecorder) GetMessages(ctx, workspaceID, userID, conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockConversationService)(nil).GetMessages), ctx, workspaceID, userID, conversationID)
}

// ListConversations mocks base method.
func (m *MockConversationService) ListConversations(ctx context.Context, filter *model.ListConversationsFilter) ([]*model.Conversation, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConversations", ctx, filter)
	ret0, _ := ret[0].([]*model.Conversation)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListConversations indicates an expected call of ListConversations.
func (mr *MockConversationServiceMockRecorder) ListConversations(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConversations", reflect.TypeOf((*MockConversationService)(nil).ListConversations), ctx, filter)
}
