// Code generated by MockGen. DO NOT EDIT.
// Source: attachment_repository.go
//
// Generated by this command:
//
//	mockgen -source=attachment_repository.go -destination=../../test/mocks/attachment_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/dexiask/dexiask/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAttachmentRepository is a mock of AttachmentRepository interface.
type MockAttachmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAttachmentRepositoryMockRecorder
	isgomock struct{}
}

// MockAttachmentRepositoryMockRecorder is the mock recorder for MockAttachmentRepository.
type MockAttachmentRepositoryMockRecorder struct {
	mock *MockAttachmentRepository
}

// NewMockAttachmentRepository creates a new mock instance.
func NewMockAttachmentRepository(ctrl *gomock.Controller) *MockAttachmentRepository {
	mock := &MockAttachmentRepository{ctrl: ctrl}
	mock.recorder = &MockAttachmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttachmentRepository) EXPECT() *MockAttachmentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAttachmentRepository) Create(ctx context.Context, input *model.StoreAttachmentInput) (*model.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(*model.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAttachmentRepositoryMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAttachmentRepository)(nil).Create), ctx, input)
}

// GetByID mocks base method.
func (m *MockAttachmentRepository) GetByID(ctx context.Context, id string) (*model.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAttachmentRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAttachmentRepository)(nil).GetByID), ctx, id)
}

// ListByConversation mocks base method.
func (m *MockAttachmentRepository) ListByConversation(ctx context.Context, conversationID string) ([]*model.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByConversation", ctx, conversationID)
	ret0, _ := ret[0].([]*model.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByConversation indicates an expected call of ListByConversation.
func (mr *MockAttachmentRepositoryMockRecorder) ListByConversation(ctx, conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByConversation", reflect.TypeOf((*MockAttachmentRepository)(nil).ListByConversation), ctx, conversationID)
}

// Reconcile mocks base method.
func (m *MockAttachmentRepository) Reconcile(ctx context.Context, uploadBucket, conversationID, messageID, newRelPathPrefix string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconcile", ctx, uploadBucket, conversationID, messageID, newRelPathPrefix)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockAttachmentRepositoryMockRecorder) Reconcile(ctx, uploadBucket, conversationID, messageID, newRelPathPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MockAttachmentRepository)(nil).Reconcile), ctx, uploadBucket, conversationID, messageID, newRelPathPrefix)
}
