// Code generated by MockGen. DO NOT EDIT.
// Source: conversation_repository.go
//
// Generated by this command:
//
//	mockgen -source=conversation_repository.go -destination=../../test/mocks/conversation_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/dexiask/dexiask/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockConversationRepository is a mock of ConversationRepository interface.
type MockConversationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockConversationRepositoryMockRecorder
	isgomock struct{}
}

// MockConversationRepositoryMockRecorder is the mock recorder for MockConversationRepository.
type MockConversationRepositoryMockRecorder struct {
	mock *MockConversationRepository
}

// NewMockConversationRepository creates a new mock instance.
func NewMockConversationRepository(ctrl *gomock.Controller) *MockConversationRepository {
	mock := &MockConversationRepository{ctrl: ctrl}
	mock.recorder = &MockConversationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConversationRepository) EXPECT() *MockConversationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockConversationRepository) Create(ctx context.Context, input *model.CreateConversationInput) (*model.Conversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(*model.Conversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockConversationRepositoryMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockConversationRepository)(nil).Create), ctx, input)
}

// GetByID mocks base method.
func (m *MockConversationRepository) GetByID(ctx context.Context, id string) (*model.Conversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Conversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockConversationRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockConversationRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockConversationRepository) List(ctx context.Context, filter *model.ListConversationsFilter) ([]*model.Conversation, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*model.Conversation)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockConversationRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockConversationRepository)(nil).List), ctx, filter)
}

// Touch mocks base method.
func (m *MockConversationRepository) Touch(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Touch", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Touch indicates an expected call of Touch.
func (mr *MockConversationRepositoryMockRecorder) Touch(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Touch", reflect.TypeOf((*MockConversationRepository)(nil).Touch), ctx, id)
}

// UpdateSessionID mocks base method.
func (m *MockConversationRepository) UpdateSessionID(ctx context.Context, id, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionID", ctx, id, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSessionID indicates an expected call of UpdateSessionID.
func (mr *MockConversationRepositoryMockRecorder) UpdateSessionID(ctx, id, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionID", reflect.TypeOf((*MockConversationRepository)(nil).UpdateSessionID), ctx, id, sessionID)
}
