// Code generated by MockGen. DO NOT EDIT.
// Source: invite_repository.go
//
// Generated by this command:
//
//	mockgen -source=invite_repository.go -destination=../../test/mocks/invite_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/dexiask/dexiask/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockInviteRepository is a mock of InviteRepository interface.
type MockInviteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInviteRepositoryMockRecorder
	isgomock struct{}
}

// MockInviteRepositoryMockRecorder is the mock recorder for MockInviteRepository.
type MockInviteRepositoryMockRecorder struct {
	mock *MockInviteRepository
}

// NewMockInviteRepository creates a new mock instance.
func NewMockInviteRepository(ctrl *gomock.Controller) *MockInviteRepository {
	mock := &MockInviteRepository{ctrl: ctrl}
	mock.recorder = &MockInviteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInviteRepository) EXPECT() *MockInviteRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInviteRepository) Create(ctx context.Context, login, createdBy string) (*model.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, login, createdBy)
	ret0, _ := ret[0].(*model.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockInviteRepositoryMockRecorder) Create(ctx, login, createdBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInviteRepository)(nil).Create), ctx, login, createdBy)
}

// Delete mocks base method.
func (m *MockInviteRepository) Delete(ctx context.Context, login string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, login)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInviteRepositoryMockRecorder) Delete(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInviteRepository)(nil).Delete), ctx, login)
}

// GetByLogin mocks base method.
func (m *MockInviteRepository) GetByLogin(ctx context.Context, login string) (*model.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLogin", ctx, login)
	ret0, _ := ret[0].(*model.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLogin indicates an expected call of GetByLogin.
func (mr *MockInviteRepositoryMockRecorder) GetByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLogin", reflect.TypeOf((*MockInviteRepository)(nil).GetByLogin), ctx, login)
}

// List mocks base method.
func (m *MockInviteRepository) List(ctx context.Context) ([]*model.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*model.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockInviteRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockInviteRepository)(nil).List), ctx)
}
