// Code generated by MockGen. DO NOT EDIT.
// Source: mcp_server_repository.go
//
// Generated by this command:
//
//	mockgen -source=mcp_server_repository.go -destination=../../test/mocks/mcp_server_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/dexiask/dexiask/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMCPServerRepository is a mock of MCPServerRepository interface.
type MockMCPServerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMCPServerRepositoryMockRecorder
	isgomock struct{}
}

// MockMCPServerRepositoryMockRecorder is the mock recorder for MockMCPServerRepository.
type MockMCPServerRepositoryMockRecorder struct {
	mock *MockMCPServerRepository
}

// NewMockMCPServerRepository creates a new mock instance.
func NewMockMCPServerRepository(ctrl *gomock.Controller) *MockMCPServerRepository {
	mock := &MockMCPServerRepository{ctrl: ctrl}
	mock.recorder = &MockMCPServerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMCPServerRepository) EXPECT() *MockMCPServerRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMCPServerRepository) Create(ctx context.Context, input *model.CreateMCPServerInput) (*model.MCPServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(*model.MCPServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMCPServerRepositoryMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMCPServerRepository)(nil).Create), ctx, input)
}

// Delete mocks base method.
func (m *MockMCPServerRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMCPServerRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMCPServerRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockMCPServerRepository) GetByID(ctx context.Context, id string) (*model.MCPServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.MCPServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMCPServerRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMCPServerRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockMCPServerRepository) List(ctx context.Context, filter *model.ListMCPServersFilter) ([]*model.MCPServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]*model.MCPServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMCPServerRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMCPServerRepository)(nil).List), ctx, filter)
}

// Update mocks base method.
func (m *MockMCPServerRepository) Update(ctx context.Context, input *model.UpdateMCPServerInput) (*model.MCPServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, input)
	ret0, _ := ret[0].(*model.MCPServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMCPServerRepositoryMockRecorder) Update(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMCPServerRepository)(nil).Update), ctx, input)
}
