// Code generated by MockGen. DO NOT EDIT.
// Source: slack_thread_repository.go
//
// Generated by this command:
//
//	mockgen -source=slack_thread_repository.go -destination=../../test/mocks/slack_thread_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSlackThreadRepository is a mock of SlackThreadRepository interface.
type MockSlackThreadRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSlackThreadRepositoryMockRecorder
	isgomock struct{}
}

// MockSlackThreadRepositoryMockRecorder is the mock recorder for MockSlackThreadRepository.
type MockSlackThreadRepositoryMockRecorder struct {
	mock *MockSlackThreadRepository
}

// NewMockSlackThreadRepository creates a new mock instance.
func NewMockSlackThreadRepository(ctrl *gomock.Controller) *MockSlackThreadRepository {
	mock := &MockSlackThreadRepository{ctrl: ctrl}
	mock.recorder = &MockSlackThreadRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlackThreadRepository) EXPECT() *MockSlackThreadRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockSlackThreadRepository) Get(ctx context.Context, threadKey string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, threadKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSlackThreadRepositoryMockRecorder) Get(ctx, threadKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSlackThreadRepository)(nil).Get), ctx, threadKey)
}

// Put mocks base method.
func (m *MockSlackThreadRepository) Put(ctx context.Context, threadKey, conversationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, threadKey, conversationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockSlackThreadRepositoryMockRecorder) Put(ctx, threadKey, conversationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockSlackThreadRepository)(nil).Put), ctx, threadKey, conversationID)
}
